###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: test1-memcached

    mysql:
      image: mysql:5.7
      container_name: test1-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=gateways
        - MYSQL_USER=gateways
        - MYSQL_PASSWORD=gateways
      ports:
        - "1027:3306"

    webserver:
      image: nginx:alpine
      container_name: test1-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: test1-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

